# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Simple Cpp Project pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Set up
    #   run: echo "${{ secrets.JFROG_TOKEN }}" | docker login anilkaiy.jfrog.io -u "${{ secrets.JFROG_USER_NAME }}" --password-stdin

    # - name: Print User and Group Info
    #   run: |
    #     echo "=== Host Environment ==="
    #     echo "User ID: $(id -u)"
    #     echo "Group ID: $(id -g)"
    #     echo "User Name: $(id -un)"
    #     echo "Group Name: $(id -gn)"
    #     docker container ls -a
  
    # - name: Test
    #   run: |
    #     python3 --version
    #     cmake --version
    #     pipx --version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker Image
      run: cd development_docker && ./build_docker.sh

    - name: Pull Docker Image
      run: |
        ./run_docker.sh --ci-build true

    # - name: Pull Docker image
    #   run: |
    #     docker pull conanio/gcc11-ubuntu16.04:2.2.2

    # - name: Run Docker container
    #   run: |
    #     docker run --rm conanio/gcc11-ubuntu16.04:2.2.2
    #     cd && ls -all
    #     tree
    # - name: Pull Docker Image
    #   run:  |
    #     docker run -d --name test_container anilkaiy.jfrog.io/docker-trial/development_docker:latest
    #     docker container ls -a

    - name: Build
      run: ./build.sh

    # - name: Run Unit-tests
    #   run: ./run_unit_tests.sh

